let msg1 = document.getElementById("message1");
let msg2 = document.getElementById("message2");
let msg3 = document.getElementById("message3");

let answer = Math.floor(Math.random()*100) + 1;
let numGuesses = 0;
let guessed_nums = [];


function play(){ 


       if (numGuesses >= 5) {
         msg2.textContent = "Du har överskridit antalet gissningar!";
         return

       }
    
       let user_guess = document.getElementById("guess").value;
      

       
 
       if(user_guess < 1 || user_guess > 100){
           alert("Du måste välja ett nummer mellan 1 and 100.");
       }
   
       else{
           guessed_nums.push(user_guess);
           numGuesses+= 1;
    //When the random number generated by the game is less than the user's input number, then the following text can be seen.
           if(user_guess < answer){
              msg1.textContent = "Numret du valt är för lågt.";
              msg2.textContent = "Antal försök: " + numGuesses;
              msg3.textContent = "Du har redan gissat på: " +
                guessed_nums;
           }
    //When the random number generated by the game exceeds the user's input number, the following text can be seen.
           else if(user_guess > answer){
              msg1.textContent = "Numret du valt är för högt.";
              msg2.textContent = "Antal försök " + numGuesses;
              msg3.textContent = "Du har redan gissat på: " +
                 guessed_nums;
           }
    //When the random number generated by the game and the user's input number are the same then the following text can be seen.
           else if(user_guess == answer){
              msg1.textContent = "Det var rätt!";
              msg2.textContent = "Numret var: " + answer;
              msg3.textContent = "Du gissade rätt efter "+ numGuesses + " försök";
              document.getElementById("my_btn").disabled = true;
           }
        }

    }